### ISSUE TITLE
NPE on Collections.unmodifiableList

### ISSUE THREAD

**Issue by ciprimare** [groupon/FeatureAdapter#33]
Version: 2.1.0

Steps to reproduce:

- call com.groupon.featureadapter.FeaturesAdapter#updateFeatureItems to update items based on model
- at least in one feature controller on build items return null(because state has not changed for example)

These steps will cause:
```
java.lang.NullPointerException
        at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1099)
        at java.util.Collections$UnmodifiableList.<init>(Collections.java:1288)
        at java.util.Collections.unmodifiableList(Collections.java:1275)
        at com.groupon.featureadapter.FeatureItems.setItemsAndGetOffset(FeatureItems.java:68)
        at com.groupon.featureadapter.FeaturesAdapter.dispatchFeatureUpdate(FeaturesAdapter.java:176)
        at com.groupon.featureadapter.FeaturesAdapter.updateFeatureItems(FeaturesAdapter.java:126)
```

**Comment by stephanenicolas** [comment]
Fixed in version 2.1.1
